import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
from pptx.oxml.ns import qn
from pptx.oxml import parse_xml
from gtts import gTTS
import nltk

# Ensure punkt is downloaded
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

# Sample input text
input_text = """
The periodic table is a tabular arrangement of all known chemical elements. It is organized based on atomic number, electron configuration, and recurring chemical properties. Elements are arranged in rows called periods and columns called groups. The periodic table helps predict the behavior of elements in chemical reactions.
"""

# Analyze text into sentences
sentences = sent_tokenize(input_text)

# Create PowerPoint
prs = Presentation()

# Title Slide
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Introduction to the Periodic Table"
subtitle.text = "Generated by Edu Video Creator"

# Content Slides with animation
for i, sentence in enumerate(sentences, 1):
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    title_shape.text = f"Slide {i}"

    tf = body_shape.text_frame
    p = tf.add_paragraph()
    p.text = sentence
    p.font.size = Pt(24)
    p.font.name = 'Calibri'

# Save presentation
pptx_file = "output_presentation.pptx"
prs.save(pptx_file)
print(f"✅ PowerPoint created: {pptx_file}")

# Convert full text to audio
tts = gTTS(text=input_text)
audio_file = "narration.mp3"
tts.save(audio_file)
print(f"✅ Audio narration created: {audio_file}")
